version: "3"

services:
  example-app:
    platform: linux/amd64
    image: example-app
    container_name: example-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
